with-expecter: true
filename: "mock_{{.InterfaceName | snakecase}}.go"
dir: "mocks/{{.InterfaceDirRelative}}"
packages:
  github.com/skip-mev/go-fast-solver/shared/evmrpc:
    interfaces:
      EVMRPCClientManager:
      EVMChainRPC:
  github.com/skip-mev/go-fast-solver/shared/oracle:
    interfaces:
      TxPriceOracle:
  github.com/skip-mev/go-fast-solver/shared/http:
    interfaces:
      Client:
  github.com/skip-mev/go-fast-solver/shared/tmrpc:
    interfaces:
      TendermintRPCClientManager:
  github.com/skip-mev/go-fast-solver/shared/cosmosgrpc:
    interfaces:
      CosmosGRPCClientConnManager:
  github.com/skip-mev/go-fast-solver/shared/signing:
    interfaces:
      Signer:
  github.com/skip-mev/go-fast-solver/shared/clients/coingecko:
    interfaces:
      PriceClient:
  github.com/skip-mev/go-fast-solver/shared/clients/utils:
    interfaces:
      HTTPClient:
      RateLimiter:
  github.com/skip-mev/go-fast-solver/shared/clients/skipgo:
    interfaces:
      SkipGoClient:
  github.com/skip-mev/go-fast-solver/shared/config:
    interfaces:
      ConfigReader:
  github.com/skip-mev/go-fast-solver/shared/signing/evm:
    interfaces:
      Builder:
  github.com/skip-mev/go-fast-solver/fundrebalancer:
    interfaces:
      Database:
  github.com/skip-mev/go-fast-solver/shared/txexecutor/evm:
    interfaces:
      EVMTxExecutor:

  # External Packages
  github.com/ethereum/go-ethereum/accounts/abi/bind:
    interfaces:
      ContractBackend:
  github.com/cosmos/gogoproto/grpc:
    interfaces:
      ClientConn:
  github.com/cometbft/cometbft/rpc/client:
    interfaces:
      Client:
  github.com/cosmos/cosmos-sdk/client:
    interfaces:
      TxConfig:
      TxBuilder:
  github.com/cosmos/cosmos-sdk/x/auth/signing:
    interfaces:
      Tx:
  github.com/cosmos/cosmos-sdk/types:
    interfaces:
      Tx:
