# IMPORTANT: Replace all values within <angle_brackets> with your specific configuration details.
# The solver will not starup with any unconfigured values in the final configuration.
metrics:
  prometheus_address: "0.0.0.0:8001"
coingecko:
  base_url: "https://pro-api.coingecko.com/api/v3/"
  # API key is optional here. If you do not have an API key, you can remove the
  # api_key option all together. If you have a coin gecko API key, we will use
  # it to get more up to date gas costs. If you specify an API key, you should
  # reduce the requests per minute and cache refresh interval according to your
  # keys limits. The values are currently set for no API key use.
  api_key: <api_key>
  requests_per_minute: 2
  cache_refresh_interval: "15m"
order_filler:
  worker_count: 10
# The fund_rebalancer config is optional. If you do not want the solver to
# rebalance your funds across chains via Skip GO (via the CCTP slow path CCTP, they
# will not be fast transferred via Skip Go Fast), you can omit the
# fund_rebalancer config all together.
fund_rebalancer:
  1:
    target_amount: <target_amount> # e.g. "1000000000"
    min_allowed_amount: <min_allowed_amount> # e.g. "500000000"
  42161:
    target_amount: <target_amount> # e.g. "1000000000"
    min_allowed_amount: <min_allowed_amount> # e.g. "500000000"
  osmosis-1:
    target_amount: <target_amount> # e.g. "1000000000"
    min_allowed_amount: <min_allowed_amount> # e.g. "500000000"
chains:
  43114:
    chain_name: "avalanche"
    chain_id: "43114"
    type: "evm"
    environment: "mainnet"
    gas_token_symbol: "AVAX"
    gas_token_decimals: 18
    gas_token_coingecko_id: "avalanche-2"
    num_block_confirmations_before_fill: <num_block_confirmations_before_fill> # e.g. 1
    hyperlane_domain: "43114"
    quick_start_num_blocks_back: <quick_start_num_blocks_back> # e.g. 1000
    max_rebalancing_gas_threshold: <max_rebalancing_gas_threshold> # e.g. 1000000
    fast_transfer_contract_address: "0xD415B02A7E91dBAf92EAa4721F9289CFB7f4E1cF"
    solver_address: <solver_address> # e.g. "0x8EB49E3D65d74967CC0Fe987FA2d015ae816352E"
    usdc_denom: "0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E"
    #### SEE shared/config/config.go for guidance on how to set the below three values per chain ####
    min_fee_bps: <min_fee_bps> # e.g. 100
    batch_uusdc_settle_up_threshold: <batch_uusdc_settle_up_threshold> # e.g. 5000000
    min_profit_margin_bps: <min_profit_margin_bps> # e.g. 50
    evm:
      rpc: <avalanche_rpc_server_url> # e.g. "https://api.avax.network/ext/bc/C/rpc"
      rpc_basic_auth_var: <server_password>
      signer_gas_balance:
        warning_threshold_wei: <warning_threshold_wei> # e.g. 1720000000000000000
        critical_threshold_wei: <critical_threshold_wei> # e.g. 580000000000000000
    relayer:
      mailbox_address: "0xFf06aFcaABaDDd1fb08371f9ccA15D73D51FeBD6"
      profitable_relay_timeout: <profitability_relay_timeout> # e.g. "5m"
      relay_cost_cap_uusdc: <relay_cost_cap_uusdc> # e.g. "1000000" uusdc

  10:
    chain_name: "optimism"
    chain_id: "10"
    type: "evm"
    environment: "mainnet"
    gas_token_symbol: "ETH"
    gas_token_decimals: 18
    gas_token_coingecko_id: "ethereum"
    num_block_confirmations_before_fill: <num_block_confirmations_before_fill> # e.g. 1
    hyperlane_domain: "10"
    quick_start_num_blocks_back: <quick_start_num_blocks_back> # e.g. 1000
    max_rebalancing_gas_threshold: <max_rebalancing_gas_threshold> # e.g. 1000000
    fast_transfer_contract_address: "0x0f479de4fd3144642f1af88e3797b1821724f703"
    solver_address: <solver_address> # e.g. "0x8EB49E3D65d74967CC0Fe987FA2d015ae816352E"
    usdc_denom: "0x0b2c639c533813f4aa9d7837caf62653d097ff85"
    #### SEE shared/config/config.go for guidance on how to set the below three values per chain ####
    min_fee_bps: <min_fee_bps> # e.g. 100
    batch_uusdc_settle_up_threshold: <batch_uusdc_settle_up_threshold> # e.g. 5000000
    min_profit_margin_bps: <min_profit_margin_bps> # e.g. 50
    evm:
      rpc: <optimism_rpc_server_url> # e.g. "https://mainnet.optimism.io"
      rpc_basic_auth_var: <server_password>
      signer_gas_balance:
        warning_threshold_wei: <warning_threshold_wei> # e.g. 180000000000000000
        critical_threshold_wei: <critical_threshold_wei> # e.g. 60000000000000000
    relayer:
      mailbox_address: "0xd4C1905BB1D26BC93DAC913e13CaCC278CdCC80D"
      profitable_relay_timeout: <profitability_relay_timeout> # e.g. "5m"
      relay_cost_cap_uusdc: <relay_cost_cap_uusdc> # e.g. "1000000" uusdc

  42161:
    chain_name: "arbitrum"
    chain_id: "42161"
    type: "evm"
    environment: "mainnet"
    gas_token_symbol: "ETH"
    gas_token_decimals: 18
    gas_token_coingecko_id: "etheruem"
    num_block_confirmations_before_fill: <num_block_confirmations_before_fill> # e.g. 1
    hyperlane_domain: "42161"
    quick_start_num_blocks_back: <quick_start_num_blocks_back> # e.g. 1000
    max_rebalancing_gas_threshold: <max_rebalancing_gas_threshold> # e.g. 1000000
    fast_transfer_contract_address: "0x23cb6147e5600c23d1fb5543916d3d5457c9b54c"
    solver_address: <solver_address> # e.g. "0x8EB49E3D65d74967CC0Fe987FA2d015ae816352E"
    usdc_denom: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
    #### SEE shared/config/config.go for guidance on how to set the below three values per chain ####
    min_fee_bps: <min_fee_bps> # e.g. 100
    batch_uusdc_settle_up_threshold: <batch_uusdc_settle_up_threshold> # e.g. 5000000
    min_profit_margin_bps: <min_profit_margin_bps> # e.g. 50
    evm:
      rpc: <arbitrum_rpc_server_url> # e.g. "https://arb1.arbitrum.io/rpc"
      rpc_basic_auth_var: <server_password>
      signer_gas_balance:
        warning_threshold_wei: <warning_threshold_wei> # e.g. 180000000000000000
        critical_threshold_wei: <critical_threshold_wei> # e.g. 60000000000000000
    relayer:
      mailbox_address: "0x979Ca5202784112f4738403dBec5D0F3B9daabB9"
      profitable_relay_timeout: <profitability_relay_timeout> # e.g. "5m"
      relay_cost_cap_uusdc: <relay_cost_cap_uusdc> # e.g. "1000000" uusdc

  osmosis-1:
    chain_name: "osmosis"
    chain_id: "osmosis-1"
    type: "cosmos"
    environment: "mainnet"
    gas_token_symbol: "OSMO"
    gas_token_decimals: 6
    gas_token_coingecko_id: "osmosis"
    fast_transfer_contract_address: "osmo1vy34lpt5zlj797w7zqdta3qfq834kapx88qtgudy7jgljztj567s73ny82"
    solver_address: <solver_address>
    hyperlane_domain: "875"
    num_block_confirmations_before_fill: <num_block_confirmations_before_fill> # e.g. 1
    max_rebalancing_gas_threshold: <max_rebalancing_gas_threshold> # e.g. 1000000
    usdc_denom: "ibc/498A0751C798A0D9A389AA3691123DADA57DAA4FE165D5C75894505B876BA6E4"
    cosmos:
      address_prefix: "osmo"
      rpc: <osmosis_rpc_server_url> # e.g. "https://rpc.osmosis.zone"
      rpc_basic_auth_var: <server_password>
      grpc: <osmosis_grpc_server_url> # e.g. "grpc.osmosis.zone:9090"
      grpc_tls_enabled: <grpc_tls_enabled> # e.g. false
      min_fill_size: <min_fill_size> # e.g. 5000000
      max_fill_size: <max_fill_size> # e.g. 10000000000
      signer_gas_balance:
        warning_threshold_wei: <warning_threshold_wei> # e.g. 42860000
        critical_threshold_wei: <critical_threshold_wei> # e.g. 14290000
      gas_price: 0.0025
      gas_denom: "uosmo"
    relayer:
      validator_announce_contract_address: "osmo147r8mfdsngswujgkr4tln9rhcrzz6yq0xn448ksd96mlcmp9wg6stvznke"
      merkle_hook_contract_address: "osmo1e765uc5mctl7rz8dzl9decl5ghgxggeqyxutkjp2xkggrg6zma3qgdq2g4"
      mailbox_address: "osmo1r6u37zv47ke4d2k9tkzun72ch466w6594kv8gqgrtmsvf7qxpm9sj95v98"
      profitable_relay_timeout: <profitability_relay_timeout> # e.g. "5m"
      relay_cost_cap_uusdc: <relay_cost_cap_uusdc> # e.g. "1000000" uusdc

  8453:
    chain_name: "base"
    chain_id: "8453"
    type: "evm"
    environment: "mainnet"
    gas_token_symbol: "ETH"
    gas_token_decimals: 18
    gas_token_coingecko_id: "ethereum"
    num_block_confirmations_before_fill: <num_block_confirmations_before_fill> # e.g. 1
    hyperlane_domain: "8453"
    quick_start_num_blocks_back: <quick_start_num_blocks_back> # e.g. 1000
    max_rebalancing_gas_threshold: <max_rebalancing_gas_threshold> # e.g. 1000000
    fast_transfer_contract_address: "0x43d090025aaa6c8693b71952b910ac55ccb56bbb"
    solver_address: <solver_address> # e.g. "0x8EB49E3D65d74967CC0Fe987FA2d015ae816352E"
    usdc_denom: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
    #### SEE shared/config/config.go for guidance on how to set the below three values per chain ####
    min_fee_bps: <min_fee_bps> # e.g. 100
    batch_uusdc_settle_up_threshold: <batch_uusdc_settle_up_threshold> # e.g. 5000000
    min_profit_margin_bps: <min_profit_margin_bps> # e.g. 50
    evm:
      rpc: <base_mainnet_rpc_server_url> # e.g. "https://mainnet.base.org"
      rpc_basic_auth_var: <server_password>
      signer_gas_balance:
        warning_threshold_wei: <warning_threshold_wei> # e.g. 180000000000000000
        critical_threshold_wei: <critical_threshold_wei> # e.g. 60000000000000000
    relayer:
      mailbox_address: "0xeA87ae93Fa0019a82A727bfd3eBd1cFCa8f64f1D"
      profitable_relay_timeout: <profitability_relay_timeout> # e.g. "5m"
      relay_cost_cap_uusdc: <relay_cost_cap_uusdc> # e.g. "1000000" uusdc

  137:
    chain_name: "polygon"
    chain_id: "137"
    type: "evm"
    environment: "mainnet"
    gas_token_symbol: "MATIC"
    gas_token_decimals: 18
    gas_token_coingecko_id: "matic-network"
    num_block_confirmations_before_fill: <num_block_confirmations_before_fill> # e.g. 1
    hyperlane_domain: "137"
    quick_start_num_blocks_back: <quick_start_num_blocks_back> # e.g. 1000
    max_rebalancing_gas_threshold: <max_rebalancing_gas_threshold> # e.g. 1000000
    fast_transfer_contract_address: "0x3ffaf8d0d33226302e3a0ae48367cf1dd2023b1f"
    solver_address: <solver_address> # e.g. "0x8EB49E3D65d74967CC0Fe987FA2d015ae816352E"
    usdc_denom: "0x3c499c542cef5e3811e1192ce70d8cc03d5c3359"
    #### SEE shared/config/config.go for guidance on how to set the below three values per chain ####
    min_fee_bps: <min_fee_bps> # e.g. 100
    batch_uusdc_settle_up_threshold: <batch_uusdc_settle_up_threshold> # e.g. 5000000
    min_profit_margin_bps: <min_profit_margin_bps> # e.g. 50
    evm:
      rpc: <polygon_mainnet_rpc_server_url> # e.g. "https://polygon-rpc.com"
      rpc_basic_auth_var: <server_password>
      signer_gas_balance:
        warning_threshold_wei: <warning_threshold_wei> # e.g. 15000000000000000000
        critical_threshold_wei: <critical_threshold_wei> # e.g. 5000000000000000000
    relayer:
      mailbox_address: "0x5d934f4e2f797775e53561bB72aca21ba36B96BB"
      profitable_relay_timeout: <profitability_relay_timeout> # e.g. "5m"
      relay_cost_cap_uusdc: <relay_cost_cap_uusdc> # e.g. "1000000" uusdc

