metrics:
  prometheus_address: "0.0.0.0:8001"
order_filler:
  worker_count: 10
chains:
  ethereum:
    chain_name: "ethereum"
    chain_id: "1"
    type: "evm"
    environment: "mainnet"
    gas_token_symbol: "ETH"
    gas_token_coingecko_id: "ethereum"
    gas_token_decimals: 18
    num_block_confirmations_before_fill: 1
    batch_uusdc_settle_up_threshold: 5000000
    evm:
      rpc: <ethereum_rpc_server_url>
      rpc_basic_auth_var: <server_password>
      contracts:
        usdc_erc20_address: 0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48
      signer_gas_balance:
        warning_threshold_wei: 4290000000000000000
        critical_threshold_wei: 1430000000000000000
  ethereum-testnet:
    chain_name: "ethereum"
    chain_id: "11155111"
    type: "evm"
    environment: "testnet"
    gas_token_symbol: "ETH"
    gas_token_decimals: 18
    evm:
      rpc: <ethereum_testnet_rpc_server_url>
      rpc_basic_auth_var: <server_password>
      contracts:
        usdc_erc20_address: 0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238
      signer_gas_balance:
        warning_threshold_wei: 250000000000000000
        critical_threshold_wei: 0
  avalanche:
    chain_name: "avalanche"
    chain_id: "43114"
    type: "evm"
    environment: "mainnet"
    gas_token_symbol: "AVAX"
    gas_token_coingecko_id: "avalanche-2"
    gas_token_decimals: 18
    batch_uusdc_settle_up_threshold: 5000000
    evm:
      rpc: <avalanche_rpc_server_url>
      rpc_basic_auth_var: <server_password>
      contracts:
        usdc_erc20_address: 0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E
      signer_gas_balance:
        warning_threshold_wei: 1720000000000000000
        critical_threshold_wei: 580000000000000000
  avalanche-testnet:
    chain_name: "avalanche"
    chain_id: "43113"
    type: evm
    environment: "testnet"
    gas_token_symbol: "AVAX"
    gas_token_decimals: 18
    evm:
      rpc: <avalanche_testnet_rpc_server_url>
      rpc_basic_auth_var: <server_password>
      contracts:
        usdc_erc20_address: 0x5425890298aed601595a70ab815c96711a31bc65
      signer_gas_balance:
        warning_threshold_wei: 1000000000000000000
        critical_threshold_wei: 0
  optimism:
    chain_name: "optimism"
    chain_id: "10"
    type: evm
    environment: "mainnet"
    gas_token_symbol: "ETH"
    gas_token_coingecko_id: "ethereum"
    gas_token_decimals: 18
    evm:
      rpc: <optimism_rpc_server_url>
      rpc_basic_auth_var: <server_password>
      contracts:
        usdc_erc20_address: 0x0b2c639c533813f4aa9d7837caf62653d097ff85
      signer_gas_balance:
        warning_threshold_wei: 180000000000000000
        critical_threshold_wei: 60000000000000000
  optimism-testnet:
    chain_name: "optimism"
    chain_id: "11155420"
    type: evm
    environment: "testnet"
    gas_token_symbol: "ETH"
    gas_token_decimals: 18
    evm:
      rpc: <optimism_testnet_rpc_server_url>
      rpc_basic_auth_var: <server_password>
      contracts:
        usdc_erc20_address: 0x5fd84259d66Cd46123540766Be93DFE6D43130D7
      signer_gas_balance:
        warning_threshold_wei: 250000000000000000
        critical_threshold_wei: 0
  arbitrum:
    chain_name: "arbitrum"
    chain_id: "42161"
    type: evm
    environment: "mainnet"
    gas_token_symbol: "ETH"
    gas_token_coingecko_id: "ethereum"
    gas_token_decimals: 18
    quick_start_num_blocks_back: 300000
    fast_transfer_contract_address: "0xD6F9F9E2C231E023fe0A8d752bc4080a112a1EbA"
    solver_address: "0x8EB49E3D65d74967CC0Fe987FA2d015ae816352E"
    hyperlane_domain: "42161"
    batch_uusdc_settle_up_threshold: 5000000
    evm:
      rpc: <arbitrum_rpc_server_url>
      rpc_basic_auth_var: <server_password>
      contracts:
        usdc_erc20_address: 0xaf88d065e77c8cC2239327C5EDb3A432268e5831
      signer_gas_balance:
        warning_threshold_wei: 180000000000000000
        critical_threshold_wei: 60000000000000000
    relayer:
      validator_announce_contract_address: "0x1df063280C4166AF9a725e3828b4dAC6c7113B08"
      merkle_hook_contract_address: "0xb49a14568f9CC440f2c7DCf7FC6766040a5eb860"
      mailbox_address: "0xB0D479FF725668bAB83aD4F24485851927Fc56D7"
  arbitrum-testnet:
    chain_name: "arbitrum"
    chain_id: "421614"
    type: evm
    environment: "testnet"
    gas_token_symbol: "ETH"
    gas_token_decimals: 18
    evm:
      rpc: <arbitrum_rpc_server_url>
      rpc_basic_auth_var: <server_password>
      contracts:
        usdc_erc20_address: 0x75faf114eafb1BDbe2F0316DF893fd58CE46AA4d
      signer_gas_balance:
        warning_threshold_wei: 250000000000000000
        critical_threshold_wei: 0
  osmosis:
    chain_name: "osmosis"
    chain_id: "osmosis-1"
    type: "cosmos"
    environment: "mainnet"
    gas_token_symbol: "OSMO"
    gas_token_coingecko_id: "osmosis"
    gas_token_decimals: 6
    fast_transfer_contract_address: "osmo19a2a86dtmlrngnjs6f0trrk3sfr9hf75n6yvlpplx6rp7z9mq4wqgmxwpm"
    solver_address: "osmo1f9qwat48ldgxrmssvpvpk3tea8l72mks20gehu"
    min_fill_size: "5000000"
    max_fill_size: "10000000000"
    usdc_denom: "ibc/498A0751C798A0D9A389AA3691123DADA57DAA4FE165D5C75894505B876BA6E4"
    hyperlane_domain: "875"
    cosmos:
      address_prefix: "osmo"
      rpc: <osmosis_rpc_server_url>
      rpc_basic_auth_var: <server_password>
      grpc: <osmosis_grpc_server_url>
      grpc_tls_enabled: false
      usdc_denom: "ibc/498A0751C798A0D9A389AA3691123DADA57DAA4FE165D5C75894505B876BA6E4"
      signer_gas_balance:
        warning_threshold_wei: 42860000
        critical_threshold_wei: 14290000
      gas_price: 0.0025
      gas_denom: "uosmo"
    relayer:
      validator_announce_contract_address: "osmo1zpnls63zlgwrt0xxat6cqtm7nvqkpc74rkr34zmvyly974htw4rq2wu98m"
      merkle_hook_contract_address: "osmo1e765uc5mctl7rz8dzl9decl5ghgxggeqyxutkjp2xkggrg6zma3qgdq2g4"
      mailbox_address: "osmo1r6u37zv47ke4d2k9tkzun72ch466w6594kv8gqgrtmsvf7qxpm9sj95v98"
  neutron:
    chain_name: "neutron"
    chain_id: "neutron-1"
    type: "cosmos"
    environment: "mainnet"
    gas_token_symbol: "NTRN"
    gas_token_coingecko_id: "neutron"
    gas_token_decimals: 6
    cosmos:
      address_prefix: "neutron"
      rpc: <neutron_rpc_server_url>
      rpc_basic_auth_var: <server_password>
      signer_gas_balance:
        warning_threshold_wei: 42860000
        critical_threshold_wei: 14290000
  noble:
    chain_name: "noble"
    chain_id: "noble-1"
    type: "cosmos"
    environment: "mainnet"
    gas_token_symbol: "USDC"
    gas_token_coingecko_id: "usd-coin"
    gas_token_decimals: 6
    cosmos:
      address_prefix: "noble"
      rpc: <noble_rpc_server_url>
      rpc_basic_auth_var: <server_password>
      signer_gas_balance:
        warning_threshold_wei: 42860000
        critical_threshold_wei: 14290000
  noble-testnet:
    chain_name: "noble"
    chain_id: "grand-1"
    type: "cosmos"
    environment: "testnet"
    gas_token_symbol: "USDC"
    gas_token_decimals: 6
    cosmos:
      address_prefix: "noble"
      rpc: <noble_testnet_rpc_server_url>
      signer_gas_balance:
        warning_threshold_wei: 0
        critical_threshold_wei: 0
  base-mainnet:
    chain_name: "base"
    chain_id: "8453"
    type: evm
    environment: "mainnet"
    gas_token_symbol: "ETH"
    gas_token_coingecko_id: "ethereum"
    gas_token_decimals: 18
    evm:
      rpc: <base_mainnet_rpc_server_url>
      rpc_basic_auth_var: <server_password>
      contracts:
        usdc_erc20_address: 0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913
      signer_gas_balance:
        warning_threshold_wei: 180000000000000000
        critical_threshold_wei: 60000000000000000
  base-testnet:
    chain_name: "base"
    chain_id: "84532"
    type: evm
    environment: "testnet"
    gas_token_symbol: "ETH"
    gas_token_decimals: 18
    evm:
      rpc: <base_testnet_rpc_server_url>
      rpc_basic_auth_var: <server_password>
      contracts:
        usdc_erc20_address: 0x036CbD53842c5426634e7929541eC2318f3dCF7e
      signer_gas_balance:
        warning_threshold_wei: 250000000000000000
        critical_threshold_wei: 0
  polygon:
    chain_name: "polygon"
    chain_id: "137"
    type: evm
    environment: "mainnet"
    gas_token_symbol: "MATIC"
    gas_token_coingecko_id: "matic-network"
    gas_token_decimals: 18
    evm:
      rpc: <polygon_mainnet_rpc_server_url>
      rpc_basic_auth_var: <server_password>
      contracts:
        usdc_erc20_address: 0x3c499c542cef5e3811e1192ce70d8cc03d5c3359
      signer_gas_balance:
        warning_threshold_wei: 15000000000000000000
        critical_threshold_wei: 5000000000000000000
      min_gas_tip_cap: 30000000000
  polygon-testnet:
    chain_name: "polygon"
    chain_id: "80002"
    type: evm
    environment: "testnet"
    gas_token_symbol: "MATIC"
    gas_token_decimals: 18
    evm:
      rpc: <polygon_testnet_rpc_server_url>
      rpc_basic_auth_var: <server_password>
      contracts:
        usdc_erc20_address: 0x41e94eb019c0762f9bfcf9fb1e58725bfb0e7582
      signer_gas_balance:
        warning_threshold_wei: 250000000000000000
        critical_threshold_wei: 0
