name: e2e
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
env:
  FOUNDRY_PROFILE: ci
  FOUNDRY_VERSION: nightly

permissions:
  contents: read

jobs:
  e2e:
    strategy:
      fail-fast: false
      matrix:
        test:
          - TestWithSolverTestSuite/TestDeploy
    name: ${{ matrix.test }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: ${{ env.FOUNDRY_VERSION }}

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"
          check-latest: true

      - name: Install dependencies and run E2E Tests
        run: |
          make tidy
          git submodule update --init --recursive
          cd tests/e2e/lib/openzeppelin-contracts && git checkout v4.8.0 
          cd ../openzeppelin-contracts-upgradeable && git checkout v4.8.0
          cd ../hyperlane-monorepo/solidity && yarn install --frozen-lockfile
          cd ../../../../.. && make e2e-test

      - name: List broadcast directory
        run: |
          ls -R broadcast/ || echo "Broadcast directory not found"

      - name: Upload run-latest.json // this contains info about all the transactions that were submitted to chain in e2e test
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-artifacts
          path: |
            broadcast/**/run-latest.json
          retention-days: 7
